USE SQLTest
GO
CREATE TABLE dbo.SKU
(
	ID INT IDENTITY,
	Code AS 's' + CAST(ID AS VARCHAR(10)) PERSISTED, 
	Name VARCHAR(50),
	CONSTRAINT PK_SKU PRIMARY KEY (ID),
	CONSTRAINT UQ_Code UNIQUE (Code)
);

CREATE TABLE dbo.Family 
(
	ID INT IDENTITY PRIMARY KEY,
	SurName VARCHAR(50),
	BudgetValue INT
);

CREATE TABLE dbo.Basket
(
	ID INT IDENTITY PRIMARY KEY,
	ID_SKU INT FOREIGN KEY REFERENCES dbo.SKU(ID),
	ID_Family INT FOREIGN KEY REFERENCES dbo.Family(ID),
	Quantity INT CHECK (Quantity >= 0),
	Value DECIMAL (10,2) CHECK (Value >= 0),
	PurchaseDate DATE DEFAULT GETDATE(),
	DiscountValuse DECIMAL(10,2)

);